In [ ]:


temperature = [35, 42, 38, 45, 39]
charge = [80, 45, 65, 30, 75]
print("Battery Readings:")
for c in charge:
    print(c, "%")
print("\nTemperature Status:")
for T in temperature:
    if T > 40:
        print("High Temperature Alert")
    else:
        print("Temperature Normal")
print("\nBattery Status:")
for C in charge:
    if C < 50:
        print("Low Battery Alert")
    else:
        print("Battery Charge Normal")
def battery_status(charge):
    if charge > 70:
        return "High"
    elif 50 <= charge <= 70:
        return "Medium"
    else:
        return "Low"
print("\nBattery Charge Levels:")
for C in charge:
    print(C, "% -", battery_status(C))


Battery Readings:
80 %
45 %
65 %
30 %
75 %

Temperature Status:
Temperature Normal
High Temperature Alert
Temperature Normal
High Temperature Alert
Temperature Normal

Battery Status:
Battery Charge Normal
Low Battery Alert
Battery Charge Normal
Low Battery Alert
Battery Charge Normal

Battery Charge Levels:
80 % - High
45 % - Low
65 % - Medium
30 % - Low
75 % - High


In [ ]:
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
print("Shape:", D.shape)
averages = np.mean(D, axis=0)
print("Average Temperature:", averages[0])
print("Average Voltage:", averages[1])
print("Average Current:", averages[2])
print("Average Charge:", averages[3])
T_max = np.max(D[:, 0])
T_min = np.min(D[:, 0])
print("Maximum Temperature:", T_max)
print("Minimum Temperature:", T_min)
V = D[:, 1]
print("Voltage column:")
print(V)
high_temp = D[D[:, 0] > 40]
print("High-temperature readings (T > 40):")
print(high_temp)
low_battery = D[D[:, 3] < 50]
print("Low-battery readings (C < 50):")
print(low_battery)


Shape: (6, 4)
Average Temperature: 38.666666666666664
Average Voltage: 387.5
Average Current: 26.166666666666668
Average Charge: 73.5
Maximum Temperature: 45
Minimum Temperature: 32
Voltage column:
[400 395 390 385 380 375]
High-temperature readings (T > 40):
[[ 42 380  30  60]
 [ 45 375  32  48]]
Low-battery readings (C < 50):
[[ 45 375  32  48]]


In [ ]:
import numpy as np

A = np.array([
    [2, 1],
    [1, 3]
])

X = np.array([
    [40],
    [25]
])

Y = A @ X
print("Y =")
print(Y)

A_transpose = A.T
print("\nTranspose of A =")
print(A_transpose)

det_A = np.linalg.det(A)
print("\nDeterminant of A =", det_A)


if det_A != 0:
    A_inverse = np.linalg.inv(A)
    print("\nInverse of A =")
    print(A_inverse)
else:
    print("\nInverse does not exist.")


B = np.array([
    [100],
    [120]
])

solution = np.linalg.solve(A, B)
print("\nSolution [x, y] =")
print(solution)


Y =
[[105]
 [115]]

Transpose of A =
[[2 1]
 [1 3]]

Determinant of A = 5.000000000000001

Inverse of A =
[[ 0.6 -0.2]
 [-0.2  0.4]]

Solution [x, y] =
[[36.]
 [28.]]


In [ ]:
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

print("========== NUMPY ANALYSIS ==========")

print("Shape of D:", D.shape)
averages = np.mean(D, axis=0)

T_avg = averages[0]
V_avg = averages[1]
I_avg = averages[2]
C_avg = averages[3]

print("Average Temperature:", T_avg)
print("Average Voltage:", V_avg)
print("Average Current:", I_avg)
print("Average Charge:", C_avg)
T_max = np.max(D[:, 0])
T_min = np.min(D[:, 0])
print("Maximum Temperature:", T_max)
print("Minimum Temperature:", T_min)
V = D[:, 1]
print("Voltage column:", V)
high_temp = D[D[:, 0] > 40]
print("High-temperature readings:")
print(high_temp)
low_battery = D[D[:, 3] < 50]
print("Low-battery readings:")
print(low_battery)
print("\n========== LINEAR ALGEBRA ==========")
A = np.array([
    [2, 1],
    [1, 3]
])
X = np.array([
    [40],
    [25]
])
Y = A @ X

print("Transformed output Y:")
print(Y)
A_transpose = A.T
print("Transpose of A:")
print(A_transpose)
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)
A_inverse = np.linalg.inv(A)
print("Inverse of A:")
print(A_inverse)
B = np.array([
    [100],
    [120]
])

solution = np.linalg.solve(A, B)

print("Solution of AX = B:")
print(solution)

x = solution[0, 0]
y = solution[1, 0]

print("x =", x)
print("y =", y)

print("\n========== CALCULUS ANALYSIS ==========")

def charge(t):
    return 100 - 2*t - 0.5*t**2

def discharge_rate(t):
    return -2 - t

rate_2 = discharge_rate(2)

rate_5 = discharge_rate(5)

print("dC/dt =", "-2 - t")
print("dC/dt at t = 2:", rate_2, "% per hour")
print("dC/dt at t = 5:", rate_5, "% per hour")

if abs(rate_5) > abs(rate_2):
    print("Interpretation: Battery is losing charge at an increasing rate.")
elif abs(rate_5) < abs(rate_2):
    print("Interpretation: Battery is losing charge at a decreasing rate.")
else:
    print("Interpretation: Battery is losing charge at a constant rate.")


print("\n========== BATTERY PERFORMANCE REPORT ==========")


high_temp_rows = D[D[:, 0] > 40]

if len(high_temp_rows) > 0:
    first_high_temp = high_temp_rows[0]
    first_high_temp_time = np.where(
        np.array([32, 35, 38, 40, 42, 45]) > 40
    )[0][0]

    print("1. Safety")
    print("First temperature exceeding 40 C:",
          first_high_temp_rows if False else first_high_temp[0], "C")
    print("First high-temperature reading occurs at data point:",
          first_high_temp_time + 1)
else:
    print("1. Safety: Temperature never exceeds 40 C.")


C_initial = D[0, 3]
C_final = D[-1, 3]

charge_loss = C_initial - C_final

print("\n2. Battery Charge")
print("Initial charge:", C_initial, "%")
print("Final charge:", C_final, "%")
print("Total charge reduction:", charge_loss, "%")


print("\n3. NumPy Analysis")
print("Average Temperature:", T_avg, "C")
print("Average Voltage:", V_avg, "V")
print("Average Current:", I_avg, "A")
print("Average Charge:", C_avg, "%")


print("\n4. Linear Algebra")
print("Y =")
print(Y)
print("x =", x)
print("y =", y)


print("\n5. Calculus")
print("dC/dt =", "-2 - t")
print("At t = 2:", rate_2, "% per hour")
print("At t = 5:", rate_5, "% per hour")

if abs(rate_5) > abs(rate_2):
    discharge_interpretation = "Battery is losing charge at an increasing rate."
else:
    discharge_interpretation = "Battery is not losing charge at an increasing rate."

print(discharge_interpretation)


if T_max > 40 and C_final < 50:
    decision = "REJECT"
elif T_max > 40:
    decision = "MONITOR"
else:
    decision = "APPROVE"

print("\n6. Final Decision")
print(decision)


========== NUMPY ANALYSIS ==========
Shape of D: (6, 4)
Average Temperature: 38.666666666666664
Average Voltage: 387.5
Average Current: 26.166666666666668
Average Charge: 73.5
Maximum Temperature: 45
Minimum Temperature: 32
Voltage column: [400 395 390 385 380 375]
High-temperature readings:
[[ 42 380  30  60]
 [ 45 375  32  48]]
Low-battery readings:
[[ 45 375  32  48]]

========== LINEAR ALGEBRA ==========
Transformed output Y:
[[105]
 [115]]
Transpose of A:
[[2 1]
 [1 3]]
Determinant of A: 5.000000000000001
Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]
Solution of AX = B:
[[36.]
 [28.]]
x = 36.0
y = 28.0

========== CALCULUS ANALYSIS ==========
dC/dt = -2 - t
dC/dt at t = 2: -4 % per hour
dC/dt at t = 5: -7 % per hour
Interpretation: Battery is losing charge at an increasing rate.

========== BATTERY PERFORMANCE REPORT ==========
1. Safety
First temperature exceeding 40 C: 42 C
First high-temperature reading occurs at data point: 5

2. Battery Charge
Initial charge: 95 %
Final charge: 48